version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db1
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 5432:5432
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - backend

  backend:
    build:
      context: ./backend/auth
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: m4rry
      POSTGRES_PASSWORD: umair123
      POSTGRES_DB: db1
      POSTGRES_HOST: postgres
      DATABASE_URL: postgres://m4rry:umair123@postgres:5432/db1
      NODE_ENV: development
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - 4000:4000

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
