version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - backend

  backend:
    build:
      context: ./backend/auth
      dockerfile: Dockerfile
    environment:
      GUARD_PORT: 4000
      DATABASE_URL: postgres://your_username:your_password@postgres:5432/your_database
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - 4000:4000

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
