#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER m4rry WITH PASSWORD 'umair123' CREATEDB;
    GRANT ALL PRIVILEGES ON DATABASE db1 TO m4rry;
    GRANT ALL PRIVILEGES ON SCHEMA public TO m4rry;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO m4rry;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO m4rry;
    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO m4rry;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO m4rry;
EOSQL
