name: Deploy to Coder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install coder CLI
        run: |
          curl -fsSL https://coder.com/install.sh | sh

      - name: Configure Coder
        run: |
          coder login ${{ secrets.CODER_URL }} --token ${{ secrets.CODER_SESSION_TOKEN }}
          # adds coder workspace Host to ~/.ssh/config
          coder config-ssh
    
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false

      - name: Deploy with Docker Compose
        run: |
          ssh coder.SampleTest 'mkdir -p ~/SampleTest'
          scp * coder.test:~/SampleTest
          ssh coder.SampleTest << 'EOF'
            cd ~/SampleTest
            docker-compose down
            docker-compose up --build -d
            cd -
          EOF
