name: Deploy to Coder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install coder CLI
        run: |
          curl -fsSL https://coder.com/install.sh | sh

      - name: Log in to Coder
        run: coder login ${{ secrets.CODER_URL }} --token ${{ secrets.CODER_SESSION_TOKEN }}
        
      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no coder@${{ secrets.CODER_HOST }} << EOF
            cd /home/coder/SampleTest
            docker-compose down
            docker-compose up --build -d
          EOF
