name: Deploy to Coder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Coder CLI
        run: |
          curl -fsSL https://coder.com/install.sh | sh

      - name: Authenticate with Coder
        run: |
          coder login ${{ secrets.CODER_URL }} --token ${{ secrets.CODER_SESSION_TOKEN }}

      - name: Deploy to Coder
        run: |
          coder envs apply --project my-project --file coder.yaml
